Starfix cli blob patch
starfixdev/starfix pull request #63
Opened 2021-07-13 13:33 UTC by fahad-israr

- Support added for opening file to specific line number.
- Handled all three IDEs separately.
- Tested to work on VS Code (on Linux  ) .
- Fixes  [#61](https://github.com/starfixdev/starfix/issues/61)

2021-07-15 08:12 UTC, maxandersen requested changes

2021-07-15 08:46 UTC, fahad-israr commented
- Doesn't work on Eclipse and Idea .
- Splitting on basis of spaces as separate command doesn't works well if you have file name with spaces in it. Have a look at URL like https://github.com/maxandersen/reallyevil/blob/main/here%20is%20a%20space.txt . Avoid manual parsing : instead use the URL Object for parsing the URL.
- Instead of embedding everything here itself try creating a new ide class/interface that does the processing as needed in specific cases .

2021-07-18 10:39 UTC, fahad-israr commented on cli/src/main/java/dev/starfix/Starfix.java
> +                    if(ide.equals("code")||ide.equals("code.cmd")){
Moved to a separate class currently and would gradually improve the structure after successfully implementing the intended functionality. Currently focussing on getting the editors to open up and point to expected line numbers.

2021-07-18 10:41 UTC, fahad-israr commented
- Now Works on IntelliJ Idea too. Tested on Linux(Ubuntu 20.x)

2021-07-21 15:14 UTC, fahad-israr commented
@maxandersen  I was successful in getting the line number thing to work on IntelliJ and Vs Code. I have been trying for eclipse but not much luck. 
I am tring to run `eclipse project_path file_path:line_number` but it isn't working . I am not sure if its not working only on my system specifically due to some issue or it doesn't work at all. 
I may a little hint from you here.

2021-07-21 23:39 UTC, maxandersen commented
It might be is specific. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=305336

' --launcher.openFile c:\workspace\MyClass.java:50' 

Seem to be whats needed on Linux if calling eclipse directly.

2021-07-24 06:16 UTC, maxandersen commented on cli/src/main/java/dev/starfix/Editor.java
> +    public static void launch_editor(Path directory, String ide, String path, String filePath) throws IOException, InterruptedException {
moving static method into a new class doen't change much - just adds another file but keep same coupling. 

should be a non-static method and have class per unique enough cases of IDE's

2021-07-24 06:17 UTC, merged

2021-07-24 06:17 UTC, maxandersen commented
mrging this as code works for more cases than current